apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    outbound:
      external:
        - host: {{env.MQ_HOST}}
          ports:
            - port: {{env.MQ_PORT}}
    inbound:
      rules:
      {{#each azure_access_inbound}}
         - application: {{this.application}}
           namespace: {{this.namespace}}
           cluster: {{this.cluster}}
      {{/each}}
  secureLogs:
    enabled: true
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 30
    periodSeconds: 10
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  envFrom:
    - secret: bidrag-samhandler-mq-password
  gcp:
    sqlInstances:
      - name: {{ database.navn }}
        type: POSTGRES_15
        databases:
          - name: bidrag-samhandler-db
            envVarPrefix: DB
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
