name: bidrag-samhandler
ingresses:
  - https://bidrag-samhandler.intern.nav.no
env:
  MQ_CONN_NAME: mpls02.adeo.no(1414)
  MQ_CHANNEL: P_BIDRAG_SAMHANDLER
  MQ_QUEUE_MANAGER: MPLS02
  MQ_TSS_REQUEST_QUEUE: queue:///QA.P415.AS10_SAMHANDLER_SERVICE?targetClient=1
access:
  outbound:
    mq-hostname: mpls02.adeo.no
azure_access_inbound:
  - application: bidrag-sak
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-aktoerregister
    namespace: bidrag
    cluser: prod-gcp