name: bidrag-samhandler
ingresses:
  - https://bidrag-samhandler.intern.nav.no
limits:
  cpu: 1000m
  memory: 2048Mi
requests:
  cpu: 500m
  memory: 1012Mi
replicas:
  max: 2
  min: 2
database:
  navn: bidrag-samhandler-prod
  tier: db-custom-1-3840
  size: 25
env:
  MQ_CONN_NAME: mpls02.adeo.no(1414)
  MQ_HOST: mpls02.adeo.no
  MQ_PORT: 1414
  MQ_CHANNEL: P_BIDRAG_SAMHANDLER
  MQ_QUEUE_MANAGER: MPLS02
  MQ_TSS_REQUEST_QUEUE: queue:///QA.P415.AS10_SAMHANDLER_SERVICE?targetClient=1
azure_access_inbound:
  - application: bidrag-sak
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-aktoerregister
    namespace: bidrag
    cluser: prod-gcp
  - application: bisys
    namespace: bidrag
    cluster: prod-fss