management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

springdoc:
  packages-to-scan: no.nav.bidrag.samhandler.controller
  swagger-ui:
    path: /
spring.main.banner-mode: off

no.nav.security.jwt:
  issuer.aad:
    discovery_url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/v2.0/.well-known/openid-configuration
    accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

ibm:
  mq:
    queueManager: ${MQ_QUEUE_MANAGER}
    channel: ${MQ_CHANNEL}
    connName: ${MQ_CONN_NAME}
    user: srvbidrag-samhandler
    password: ${MQ_PASSWORD}
    application-name: BIDRAG-SAMHANDLER
    tssRequestQueue: ${MQ_TSS_REQUEST_QUEUE}
    use-authentication-m-q-c-s-p: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_JDBC_URL}
    hikari:
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 1
      data-source-properties:
        ssl: true
        sslmode: ${DB_SSLMODE}
        sslcert: ${DB_SSLCERT}
        sslkey: ${DB_SSLKEY_PK8}
        sslrootcert: ${DB_SSLROOTCERT}
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    database: postgresql
    open-in-view: false
