management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

springdoc:
  packages-to-scan: no.nav.bidrag.samhandler.controller
spring.main.banner-mode: off

no.nav.security.jwt:
  issuer.aad:
    discovery_url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/v2.0/.well-known/openid-configuration
    accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

ibm:
  mq:
    queueManager: ${MQ_QUEUE_MANAGER}
    channel: ${MQ_CHANNEL}
    connName: ${MQ_CONN_NAME}
    user: srvbidrag-samhandler
    password: ${MQ_PASSWORD}
    application-name: BIDRAG-SAMHANDLER
    tssRequestQueue: ${MQ_TSS_REQUEST_QUEUE}
    use-authentication-m-q-c-s-p: true

mq:
  queueManager: ${MQ_QUEUE_MANAGER}
  channel: ${MQ_CHANNEL}
  host: b27apvl220.preprod.local1413
  port: 1413
  user: srvbidrag-samhandler
  password: ${MQ_PASSWORD}
  application-name: BIDRAG-SAMHANDLER
  tssRequestQueue: ${MQ_TSS_REQUEST_QUEUE}
  backOffInitialInterval: 15000
  backOffMaxInterval: 300000
  timeout: 15000

