name: Deploy Q4
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches:
      - '**'
      - '!main'
      - '!q1/**'
      - '!Q1/**'
      - '!q2/**'
      - '!Q2/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to Q4"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: q4.yaml