name: Deploy feature
on:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_deploy:
    name: "Build and deploy to feature"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy_feature.yaml@main
    secrets: inherit