name: Deploy Q1
on:
  workflow_dispatch:
  schedule:
    - cron : '0 2 * * 1'
  push:
    branches:
      - 'q1/**'
      - 'Q1/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to Q1"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: q1.yaml