name: Deploy to dev
on:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy_main.yaml@main
    secrets: inherit